# Generated by Django 3.2.16 on 2022-12-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
