# Generated by Django 3.2.16 on 2022-12-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0003_stripeplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='StripePlan',
        ),
    ]
