# Generated by Django 3.2.16 on 2022-12-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0004_auto_20221214_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='active_status',
        ),
    ]
