# Generated by Django 3.2.16 on 2022-12-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0005_remove_stripecustomer_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripeProductId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
