# Generated by Django 3.2.16 on 2022-12-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0007_auto_20221214_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
