# Generated by Django 3.2.16 on 2022-12-14 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0008_stripecustomer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='status',
        ),
    ]
