# Generated by Django 3.2.16 on 2022-12-23 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0009_remove_stripecustomer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('product_name', models.CharField(max_length=255)),
                ('point', models.PositiveIntegerField()),
                ('product_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripeProductId',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripeSubscriptionId',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='trial_end',
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='customer_point',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_id', models.TextField()),
                ('price_amount', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashApp.product')),
            ],
        ),
    ]
