# Generated by Django 3.2.16 on 2022-12-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0009_remove_stripecustomer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripeProductId',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripeSubscriptionId',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='subscription_end',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='trial_end',
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='customer_point',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
