# Generated by Django 3.2.16 on 2022-12-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0010_auto_20221223_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
