# Generated by Django 3.2.16 on 2022-12-28 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashApp', '0011_customerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
