# Generated by Django 3.2.16 on 2022-12-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashApp', '0012_alter_stripecustomer_customer_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='customer_point',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
